dist: trusty

language: python

python:
    - 2.7
    - 3.5

addons:
    apt:
        packages:
            liblapacke-dev

install: 
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install .

script:
    - python -m pytest
