language: python

sudo: required

python:
        - 2.7
        - 3.5

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y liblapacke-devel

install: 
        - pip install --upgrade pip
        - pip install https://github.com/rscohn2/ibench/archive/master.zip
        - pip install .

script:
        - python -m pytest
