dist: precise

language: python

python:
    - 2.7
    - 3.5

addons:
    apt:
        packages:
            liblapacke-dev

install: 
    - pip install --upgrade pip
    - pip install https://github.com/rscohn2/ibench/archive/master.zip
    - pip install .

script:
    - python -m pytest
